# Site settings
title: Tech Things
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
copyright_name: ByMe
description: "Covering new technology. Consultant at Red Hat"
# baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://mcanoy.github.io
twitter_username: whereswendel
github_username:  mcanoy
# email_username:  your-email@yourdomain.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
