# Site settings
title: Tech Things
header-img: img/brown-cloud.png
email: your-email@yourdomain.com
copyright_name: Kevin
description: "New technology. Wears a Red Hat. It has a claw on it"
url: "http://mcanoy.github.io"
twitter_username: whereswendel
github_username:  mcanoy
# email_username:  your-email@yourdomain.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-2669425-4

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
